#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

command="/usr/bin/proxysql"
name="ProxySQL"
command_args="-c /etc/proxysql.cnf -D ${DATADIR}"
pidfile="${DATADIR}/proxysql.pid"
rc_ulimit=" -n 102400"
extra_stopped_commands="initial"

depend() {
	need net
}

initial() {
	command_args="--initial ${command_args}"
	start
}

stop_pre() {
	# Note: we send a kill to all the processes, not just to the child
	pkill --signal TERM -P $(<${pidfile})
}
